name: certora-arbitrum

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check key
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
        run: echo "key length" ${#CERTORAKEY}

      - name: Install python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }

      - name: Install java
        uses: actions/setup-java@v1
        with: { java-version: "11", java-package: jre }

      - name: Install certora cli
        run: pip install certora-cli
        
      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.10/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.10
      
      - name: Verify rule ${{ matrix.rule }}
        run: |
          cd certora
          touch applyHarness.patch
          make munged
          cd ..
          echo "key length" ${#CERTORAKEY}
          sh certora/scripts/${{ matrix.rule }}
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
          
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        rule:
          - verifyArbitrum.sh executedValidTransition2
          - verifyArbitrum.sh onlyCancelCanCancel
          - verifyArbitrum.sh onlyQueuedAreExecuted
          - verifyArbitrum.sh expiredForever
          - verifyArbitrum.sh actionNotCanceledAndExecuted
          - verifyArbitrum.sh properDelay
          - verifyArbitrum.sh notCanceledNotExecuted 
          - verifyArbitrum.sh minDelayLtMaxDelay
          - verifyArbitrum.sh whoChangedStateVariables
          - verifyArbitrum.sh executeCannotCancel
          - verifyArbitrum.sh whoChangesActionsSetState
          - verifyArbitrum.sh canceledForever
          - verifyArbitrum.sh executedForever
          - verifyArbitrum.sh executeRevertsBeforeDelay
          - verifyArbitrum.sh noIncarnations1 noIncarnations2 noIncarnations3
          - verifyArbitrum.sh actionDuplicate holdYourHorses executeFailsIfExpired executedValidTransition1 queuePriviliged afterQueueHashQueued queue2Reachability cancelPriviliged independentQueuedActions queueCannotCancel queueDoesntModifyStateVariables queuedStateConsistency queuedChangedCounter sameExecutionTimesReverts cancelExclusive
